### PR TITLE
EncryptionUsingKey

### PR DESCRIPTION
**Pull request by CyberPidgi**
Hi I would like to commit my cipher which uses a key to randomize the letters of the text which can only be decrypted with possession of the key.

### CODE REVIEW

**Comment by sarthakg043** [comment]
@CyberPidgi Please provide a `readme.md` file explaining your code and the algorithm in detail.
Including all the mathematics behind it.

**Comment by CyberPidgi** [comment]
i have added a readme.md as requested.

**Comment by CyberPidgi** [comment]
@sarthakg043 please do accept my pull request

**Comment by sarthakg043** [comment]
Merged, but you need to update the readme, with an example,explaining the working of the algorithm.
Also format the readme file with proper MD syntax

**Pull request merged**
